#Set the name to Reuse other workflow and add a manual trigger
name: Reuse other workflow
#Add a job call-workflow that uses the reusable workflow and passes in your user name as an input parameter.
on: [workflow_dispatch]
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@octocat'
#Add another job use-output that writes the output parameter current-time to the console. (Hint: use the needs context to access the output)
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
